### ISSUE TITLE
Run VPP forwarder as non-root

### ISSUE THREAD

**Issue by rpiceage** [networkservicemesh/cmd-forwarder-vpp#127]
For security reasons I want to start the VPP forwarder container as non root. Can you provide some info if it can be done, what capabilities are needed, etc?
Thanks for the help

**Comment by edwarnicke** [comment]
@rpiceage Do you mean non-root or non-privileged?

**Comment by rpiceage** [comment]
@edwarnicke I mean a non-root user, but it would also be nice to have a defined set of capabilities instead of privileged mode.

**Comment by edwarnicke** [comment]
@rpiceage To my understanding... in modern linux... its capabilities that matter, not uid.  Which is why I was asking.  Running as 'root' is neither here nor there.  Running in privileged mode conveys a lot of power.  I'm almost certain we could scale back to CAP_NET_ADMIN if that meets your needs... but one of the reasons we simply went with privileged mode is CAP_NET_ADMIN has such a long history of letting folks break out to CAP_SYS_ADMIN that its generally not considered functionally all that different in security circles... and so 'privileged' seemed to better convey things.

**Comment by rpiceage** [comment]
@edwarnicke thanks for your answer.
Yes, you are right, the user is not the issue here. I can start the forwarder with my non-root user, but VPP then needs some capabilities and folders to run properly, which I have to add. CAP_NET_ADMIN is fine, although I understand your point about it. For our requirements, though, it's better to have a clearly defined set of capabilities than privileged mode.

**Comment by edwarnicke** [comment]
@rpiceage Got it :)  There are two schools of thought on that (neither of them right or wrong, just different perspectives).

1. Setting CAP_NET_ADMIN provides a false sense of security, and may lull folks into being to complacent.
2. You should have the most narrowly scoped capabilities you can get away with

I tend towards #1, you tend towards #2.  At a minimum, we need to make sure everything works properly with CAP_NET_ADMIN and then we can quibble over our minor differences from there :)

**Comment by rpiceage** [comment]
@edwarnicke Agreed :)

**Comment by edwarnicke** [comment]
@rpiceage So... digging around a little bit (ie, trying it) it seems that we would minimally need CAP_NET_ADMIN and CAP_IPC_LOCK.  Is CAP_IPC_LOCK also agreeable to you?

In addition, it looks like we will need to fix a few places (like MTU setting for AF_PACKET) where VPP is writing to /sys/ rather than using netlink to set MTUs.

**Comment by edwarnicke** [comment]
@rpiceage Looks like the AF_PACKET related issue has been fixed upstream in VPP already:

https://gerrit.fd.io/r/c/vpp/+/31818

So with any good fortune, its a matter of respinning our vpp containers to include that patch :)

**Comment by rpiceage** [comment]
@edwarnicke thanks for the update, sounds good :)
CAP_IPC_LOCK is also OK.

**Comment by edwarnicke** [comment]
@rpiceage  OK... after fixing the AF_PACKET issue and continuing on... I discovered something that, unfortunately, means that any forwarder which want to support kernel interfaces will have to have CAP_SYS_ADMIN:

From the [linux capabilities manpage](https://man7.org/linux/man-pages/man7/capabilities.7.html)
> call setns(2) (requires CAP_SYS_ADMIN in the target namespace);

Since setns is, fundamentally, how kernel interfaces get inserted into the Pods netns... if you want to do that, you have to have CAP_SYS_ADMIN... its sadly unavoidable :(

**Comment by rpiceage** [comment]
@edwarnicke OK, thanks for the update. If we can document exactly which capabilities are really needed then we'll be fine.

**Comment by edwarnicke** [comment]
@rpiceage Do you have a preference as to *where* you'd like it documented?

**Comment by rpiceage** [comment]
@edwarnicke No, I meant if you can provide the list of the capabilities, then we can document the stuff properly on our part.

**Comment by edwarnicke** [comment]
@rpiceage To the best of my awareness in order for a Forwarder to insert kernel interfaces into the Pods Network Namespace CAP_SYS_ADMIN (which incorporates all capabilities) is required.   

For normal non-kernel-interface inserting VPP based NSEs we don't need any special capabilities.

Does that answer your question?

**Comment by rpiceage** [comment]
@edwarnicke Yes, thanks for the clarification and help. I think we can close this issue.
